#!/usr/bin/env bash
#
# SemanticClaws / Simply Semantics - Secure Rootless Podman Setup
# ----------------------------------------------------------------
# Company: Simply Semantics (www.simplysemantics.com)
# Purpose: Small, trusted, low-cost SaaS component for local AI tooling
#          High-volume adoption focus — keep it simple, private, secure.
#
# This script sets up a rootless Podman environment for OpenClaw (or similar local AI).
# Designed for US/North America market: emphasizes data locality (no cloud telemetry),
# least privilege, auditability, and compliance-friendly design (helps with CCPA etc.).
#
# Security highlights:
# - Rootless Podman (no daemon, user namespaces)
# - Dedicated non-root user with strict permissions
# - Secure temp files outside /tmp
# - Auto subuid/subgid setup (with safety checks)
# - Vulnerability scanning hook (Trivy if available)
# - Detailed logging for auditing
#
# REVIEW BEFORE RUNNING: curl | bash is convenient but risky.
# Best: download → inspect → chmod +x → ./setup-podman.sh
#
# Version: 2026-02 - SemanticClaws hardened edition

set -euo pipefail

# -------------------------------
# Branding & Configuration
# -------------------------------
readonly COMPANY="Simply Semantics"
readonly PROJECT="SemanticClaws"
readonly OPENCLAW_USER="openclaw"
readonly OPENCLAW_HOME="/opt/${PROJECT:-openclaw}"
readonly LOG_FILE="${OPENCLAW_HOME}/setup.log"
readonly TMP_DIR="${OPENCLAW_HOME}/.tmp"

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

# -------------------------------
# Helper Functions
# -------------------------------
log() {
    local level="$1"
    shift
    printf "[%s] %s: %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$level" "$*" | tee -a "$LOG_FILE"
}

info()  { log "INFO"  "$@"; }
warn()  { log "WARN"  "${YELLOW}$*${NC}"; }
error() { log "ERROR" "${RED}$*${NC}" >&2; exit 1; }

command_exists() { command -v "$1" >/dev/null 2>&1; }

require_cmd() {
    command_exists "$1" || error "$1 is required but not installed. Please install it first."
}

run_as_openclaw() {
    sudo -u "$OPENCLAW_USER" -- "$@"
}

run_root() {
    sudo "$@"
}

# -------------------------------
# Main Setup
# -------------------------------
main() {
    info "Starting ${PROJECT} secure rootless Podman setup by ${COMPANY}"

    # Create secure home + log dir
    run_root mkdir -p "$OPENCLAW_HOME" "$TMP_DIR"
    run_root chown -R "$OPENCLAW_USER":"$OPENCLAW_USER" "$OPENCLAW_HOME"
    run_root chmod 700 "$OPENCLAW_HOME" "$TMP_DIR"

    # Redirect all output to log too
    exec > >(tee -a "$LOG_FILE") 2>&1

    # 1. Ensure Podman is installed
    require_cmd podman
    podman --version || error "Podman not functional"

    # 2. Create dedicated user if missing
    if ! id "$OPENCLAW_USER" >/dev/null 2>&1; then
        info "Creating dedicated user: $OPENCLAW_USER"
        run_root useradd --system --shell /usr/sbin/nologin \
            --home-dir "$OPENCLAW_HOME" --create-home \
            "$OPENCLAW_USER" || error "Failed to create user"
    fi

    # 3. Configure subuid/subgid if missing (critical for rootless)
    if ! grep -q "^${OPENCLAW_USER}:" /etc/subuid || ! grep -q "^${OPENCLAW_USER}:" /etc/subgid; then
        warn "subuid/subgid not configured for $OPENCLAW_USER — attempting safe auto-setup"
        local range_start=100000
        local range_size=65536

        # Simple conflict check
        if grep -q "${range_start}" /etc/subuid || grep -q "${range_start}" /etc/subgid; then
            error "UID/GID range conflict at ${range_start}. Manually configure /etc/subuid and /etc/subgid."
        fi

        run_root sh -c "echo '${OPENCLAW_USER}:${range_start}:${range_size}' >> /etc/subuid"
        run_root sh -c "echo '${OPENCLAW_USER}:${range_start}:${range_size}' >> /etc/subgid"
        info "Added subuid/subgid range ${range_start}-${range_start+$range_size-1}"
    else
        info "subuid/subgid already configured"
    fi

    # 4. Generate secure gateway token
    info "Generating secure gateway token..."
    local token
    if command_exists openssl; then
        token=$(openssl rand -base64 48 | tr -d '\n')
    elif command_exists python3; then
        token=$(python3 -c "import secrets; print(secrets.token_urlsafe(64))")
    else
        token=$(head -c 64 /dev/urandom | base64 | tr -d '\n')
    fi
    [ -z "$token" ] && error "Failed to generate token"

    # 5. Create secure .env
    local env_file="${OPENCLAW_HOME}/.env"
    cat > "$env_file" << EOF
# Generated by ${PROJECT} setup - ${COMPANY}
OPENCLAW_GATEWAY_TOKEN=${token}
OPENCLAW_HOME=${OPENCLAW_HOME}
# Add other vars as needed (e.g., model paths, ports)
EOF
    run_root chown "$OPENCLAW_USER":"$OPENCLAW_USER" "$env_file"
    run_root chmod 600 "$env_file"
    info "Secure .env created at ${env_file}"

    # 6. Build the image (assumes Dockerfile exists in current dir or repo)
    info "Building container image..."
    local image_name="${PROJECT:-openclaw}:local"
    TMP_IMAGE="${TMP_DIR}/$(mktemp -u build-XXXXXX.tar)"

    trap 'rm -f "$TMP_IMAGE" 2>/dev/null' EXIT

    run_as_openclaw podman build -t "$image_name" -f Dockerfile . \
        || error "Image build failed"

    # Optional: vulnerability scan (Trivy preferred)
    if command_exists trivy; then
        info "Running Trivy vulnerability scan..."
        trivy image --exit-code 1 --no-progress --severity CRITICAL,HIGH "$image_name" \
            || warn "Trivy found issues — review before production use"
    else
        warn "Trivy not found — skipping vuln scan (install for better security)"
    fi

    # 7. Basic systemd quadlet recommendation
    info "Setup complete. For reliable auto-start, use systemd quadlets (recommended):"
    info "  → Place .container / .service files in ~/.config/containers/systemd/"
    info "  → Example: podman generate systemd --new --name --files $image_name"
    info "Network note: Podman 5.0+ defaults to pasta (more secure than slirp4netns). Consider --network=pasta"

    info "${GREEN}Setup finished successfully!${NC}"
    info "Logs: ${LOG_FILE}"
    info "Review everything — especially token and permissions — before exposing ports."
    info "For enterprise use or SaaS resale: consider adding secret rotation, SELinux, Falco monitoring."
}

main "$@"