#!/usr/bin/env bash
#
# SemanticClaws / Simply Semantics - Secure Rootless Podman Setup
# ----------------------------------------------------------------
# Company: Simply Semantics (www.simplysemantics.com)
# Purpose: Small, trusted, low-cost SaaS component for local AI tooling
#          High-volume adoption focus — keep it simple, private, secure.
#
# This script clones upstream OpenClaw, uses their official Dockerfile,
# applies hardening (secure token, logging, macOS compatibility), and
# builds a branded local image: semanticclaws:local
#
# Security highlights:
# - Rootless Podman (no daemon, user namespaces)
# - Secure temp files & token generation
# - macOS-friendly (skips Linux-only user/subuid steps)
# - Detailed logging for auditing
#
# Version: 2025-02 - SemanticClaws hardened edition (upstream + memory fix)

set -euo pipefail

# -------------------------------
# Branding & Configuration
# -------------------------------
readonly COMPANY="Simply Semantics"
readonly PROJECT="semantic-claws"
readonly IMAGE_NAME="${PROJECT}:local"
readonly UPSTREAM_REPO="https://github.com/openclaw/openclaw.git"
readonly UPSTREAM_REF="main"  # Pin to tag if needed, e.g., "vX.Y.Z"
readonly WORK_DIR="$(mktemp -d -t semanticclaws-setup.XXXXXX)"
readonly OPENCLAW_HOME="${HOME}/.local/share/${PROJECT}"
readonly LOG_FILE="${OPENCLAW_HOME}/setup.log"
readonly TMP_DIR="${OPENCLAW_HOME}/.tmp"

# Detect macOS
readonly IS_MACOS=$([[ "$(uname -s)" == "Darwin" ]] && echo true || echo false)

# Colors
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

# -------------------------------
# Helper Functions
# -------------------------------
log() {
    local level="$1"
    shift
    printf "[%s] %s: %s\n" "$(date '+%Y-%m-%d %H:%M:%S')" "$level" "$*" | tee -a "$LOG_FILE"
}

info()  { log "INFO"  "$@"; }
warn()  { log "WARN"  "${YELLOW}$*${NC}"; }
error() { log "ERROR" "${RED}$*${NC}" >&2; exit 1; }

command_exists() { command -v "$1" >/dev/null 2>&1; }

require_cmd() {
    command_exists "$1" || error "$1 is required but not installed. Please install it first."
}

cleanup() {
    rm -rf "$WORK_DIR" 2>/dev/null || true
    info "Cleaned up temporary clone directory."
}
trap cleanup EXIT INT TERM

increase_podman_memory() {
    if $IS_MACOS; then
        info "Checking Podman machine memory (macOS VM)..."
        local current_mem
        current_mem=$(podman machine inspect --format '{{.Resources.Memory}}' podman-machine-default 2>/dev/null || echo "unknown")
        if [[ "$current_mem" == "unknown" ]]; then
            info "Podman machine not found — initializing with higher memory..."
            podman machine init --memory 8192 podman-machine-default || warn "Init failed — run 'podman machine init --memory 8192' manually if needed"
            podman machine start podman-machine-default
        elif [[ "$current_mem" -lt 8192 ]]; then
            info "Increasing Podman VM memory to 8GB (from ~$current_mem MB) for build stability..."
            podman machine stop podman-machine-default || true
            podman machine set --memory 8192 podman-machine-default
            podman machine start podman-machine-default
        else
            info "Podman VM memory already sufficient (~$current_mem MB)"
        fi
    fi
}

# -------------------------------
# Main Setup
# -------------------------------
main() {
    mkdir -p "$OPENCLAW_HOME" "$TMP_DIR" || error "Failed to create $OPENCLAW_HOME"
    chmod 700 "$OPENCLAW_HOME" "$TMP_DIR"

    info "Starting ${PROJECT} secure rootless Podman setup by ${COMPANY}"
    exec > >(tee -a "$LOG_FILE") 2>&1

    if $IS_MACOS; then
        info "macOS detected — running fully rootless in Podman VM."
    fi

    require_cmd podman
    podman --version || error "Podman not functional"

    increase_podman_memory  # Fix VM memory for heavy builds

    info "Cloning upstream OpenClaw repo (${UPSTREAM_REF})..."
    require_cmd git
    git clone --depth 1 --branch "${UPSTREAM_REF}" "${UPSTREAM_REPO}" "$WORK_DIR" \
        || error "Failed to clone upstream repo"

    cd "$WORK_DIR" || error "Failed to cd into clone dir"

    info "Generating secure gateway token..."
    local token
    if command_exists openssl; then
        token=$(openssl rand -base64 48 | tr -d '\n')
    elif command_exists python3; then
        token=$(python3 -c "import secrets; print(secrets.token_urlsafe(64))")
    else
        token=$(head -c 64 /dev/urandom | base64 | tr -d '\n')
    fi
    [ -z "$token" ] && error "Failed to generate token"

    local env_file="${OPENCLAW_HOME}/.env"
    cat > "$env_file" << EOF
# Generated by ${PROJECT} setup - ${COMPANY}
OPENCLAW_GATEWAY_TOKEN=${token}
OPENCLAW_HOME=${OPENCLAW_HOME}
# Add other vars as needed (e.g., model paths, ports)
EOF
    chmod 600 "$env_file"
    info "Secure .env created at ${env_file}"

    info "Building branded image using upstream Dockerfile with increased Node heap..."
    # Use upstream Dockerfile but inject higher heap limit for build stability
    podman build \
        --build-arg NODE_OPTIONS="--max-old-space-size=6144" \
        -t "$IMAGE_NAME" \
        -f Dockerfile . \
        || error "Image build failed (upstream Dockerfile + heap fix)"

    info "${GREEN}Setup finished successfully!${NC}"
    info "Image: ${IMAGE_NAME}"
    info "Logs: ${LOG_FILE}"
    info "Data & config: ${OPENCLAW_HOME}"
    info "For production: systemd quadlets (Linux) or Podman Desktop auto-start (macOS)."
    info "Review token in .env and test with:"
    info "  podman run -d \\"
    info "    --name semantic-claws \\"
    info "    -p 18789:18789 -p 18791:18791 \\"
    info "    -v ${OPENCLAW_HOME}:/data \\"
    info "    ${IMAGE_NAME}"
    info "  Then open dashboard at http://localhost:18789"
    info "  or connect via ws://localhost:18789"

}

main "$@"